strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  inputs:
    cmakeArgs: '-DBUILD_SHARED_LIBS=ON ..'
- task: CMake@1
  inputs:
    cmakeArgs: '--build .'
