jobs:
  - job: windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      maxParallel: 2
      matrix:
        x86-Debug:
          buildPlatform: 'Win32'
        x64-Release:
          buildPlatform: 'x64'
    steps:
    - task: CMake@1
      displayName: 'CMake configure'
      inputs:
        cmakeArgs: '-G "Visual Studio 15 2017" -A $(buildPlatform) -DCMAKE_BUILD_TYPE=Release .. '
    - task: CMake@1
      displayName: 'CMake build'
      inputs:
        cmakeArgs: '--build . --config Release'

  - job: linux
    pool:
      vmImage: Ubuntu-16.04
    steps:
    - script: |
        sudo apt update
        sudo apt install clang
      displayName: 'Install dependencies'
    - script: 'mkdir build'
      displayName: 'Create build directory'
    - task: CMake@1
      displayName: 'CMake configure'
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release ..'
    - task: CMake@1
      displayName: 'CMake build'
      inputs:
        cmakeArgs: '--build . --config Release'